### ISSUE TITLE
update

### ISSUE THREAD

**Issue by qq1053831109** [gisellevonbingen/MdxModelRenderer#1]
update jme3

**Comment by gisellevonbingen** [comment]
that update has any merit?

**Comment by qq1053831109** [comment]
jme3 is a java 3d game engine！ i want use mdx model for Independent 3d game

**Comment by gisellevonbingen** [comment]
I tried to test the engine, but it was too difficult for me.
Maybe I haven't done Java for a long time.

There are many other things to do while studying.
so sorry.

it seems that the vertex stored in the Geoset of the MdxModel will be drawn just by adding it to the 'Mesh'.

**Comment by qq1053831109** [comment]
oh!thats sad,if have this libs, it is Great things for jme3 programmer!
